# Generated by Django 4.1.4 on 2022-12-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inst_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='media/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='media/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='media/')),
                ('info_name', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('sale', 'sale'), ('new', 'new')], max_length=50, null=True)),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('pro_quantity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('strong_text', models.TextField(blank=True, null=True)),
                ('text', models.TextField()),
                ('text2', models.TextField()),
                ('sing_img', models.ImageField(upload_to='media/')),
                ('img', models.ImageField(upload_to='media/')),
                ('video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type_of_job', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='media/')),
                ('info', models.TextField()),
                ('face_link', models.CharField(blank=True, max_length=200, null=True)),
                ('inst_link', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
