# Generated by Django 4.1.4 on 2022-12-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment_shopuser_delete_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='img',
            field=models.ImageField(default='images/blog-single-author2.png', upload_to=''),
        ),
    ]
